# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
  s3_bucket: "grammar-board-dev"

production:
  s3_bucket: "grammar-board-pro"

s3_region:  "us-west-1"
s3_access_key_id: "AKIAIIV5XGWHFNSAZYIQ"
s3_secret_access_key: "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"

#New Relic license: 45a27837aea19af651dd4ffeb6f68ceb5dfc2c68
